/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.gudangkopi.view;

/**
 *
 * @author Deubin
 */
public class FormEditBarang extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormEditBarang.class.getName());

    /**
     * Creates new form FormEditBarang
     */
    public FormEditBarang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private String idBarangTerpilih;

    public void siapkanDataForm(String id, String grade, String harga, String stok) {
        this.idBarangTerpilih = id;
        
        cbGradeKopi.setSelectedItem(grade);
        
        String hargaMurni = harga.replace("Rp ", "").trim();
        String stokMurni = stok.replace(" Kg", "").trim();
        
        txtHarga.setText(hargaMurni);
        txtStok.setText(stokMurni);
    }
    
    private final com.mycompany.gudangkopi.controller.InventarisKopiController kopiController = 
            new com.mycompany.gudangkopi.controller.InventarisKopiController();

    public void gradeKopi() {
        cbGradeKopi.removeAllItems();
        java.util.List<com.mycompany.gudangkopi.model.InventarisKopi> listKopi = kopiController.getAllInventaris();
        
        for (com.mycompany.gudangkopi.model.InventarisKopi k : listKopi) {
            boolean sudahAda = false;
            for (int i = 0; i < cbGradeKopi.getItemCount(); i++) {
                if (cbGradeKopi.getItemAt(i).equals(k.getGradeKopi())) {
                    sudahAda = true;
                    break;
                }
            }
            if (!sudahAda && k.getGradeKopi() != null) {
                cbGradeKopi.addItem(k.getGradeKopi());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbGradeKopi = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Edit Harga & Stok");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Grade Kopi");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Stok");

        cbGradeKopi.addActionListener(this::cbGradeKopiActionPerformed);

        txtHarga.setText("Harga");
        txtHarga.addActionListener(this::txtHargaActionPerformed);

        txtStok.setText("Stok");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbGradeKopi, 0, 172, Short.MAX_VALUE)
                            .addComponent(txtHarga)
                            .addComponent(txtStok)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGradeKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSimpan))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbGradeKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGradeKopiActionPerformed
        // TODO add your handling code here:
        String gradeTerpilih = cbGradeKopi.getSelectedItem().toString();

        java.util.List<com.mycompany.gudangkopi.model.InventarisKopi> listKopi = kopiController.getAllInventaris();
    
        for (com.mycompany.gudangkopi.model.InventarisKopi k : listKopi) {
            if (k.getGradeKopi().equalsIgnoreCase(gradeTerpilih)) {
                // update tampilan teks
                txtHarga.setText(String.format("%.0f", k.getHargaPerKg()));
                txtStok.setText(String.format("%.0f", k.getStok()));

                this.idBarangTerpilih = String.valueOf(k.getIdBarang());
                break;
            }
        }
    }//GEN-LAST:event_cbGradeKopiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (txtHarga.getText().trim().isEmpty() || txtStok.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Harga dan Stok tidak boleh kosong!", 
                    "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (idBarangTerpilih == null || idBarangTerpilih.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Silakan pilih Grade Kopi terlebih dahulu!", 
                    "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int idBarang = Integer.parseInt(idBarangTerpilih);
            double hargaBaru = Double.parseDouble(txtHarga.getText().trim());
            double stokBaru = Double.parseDouble(txtStok.getText().trim());
            String gradeTerpilih = cbGradeKopi.getSelectedItem().toString();

            com.mycompany.gudangkopi.model.InventarisKopi kopiEdit = 
                new com.mycompany.gudangkopi.model.InventarisKopi(idBarangTerpilih, gradeTerpilih, hargaBaru, stokBaru);

            boolean berhasil = kopiController.updateInventaris(kopiEdit); 

            if (berhasil) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Inventaris Kopi berhasil diperbarui!");
    
                java.awt.Window[] windows = java.awt.Window.getWindows();
                for (java.awt.Window window : windows) {
                    if (window.getClass().getName().equals("com.mycompany.gudangkopi.view.dashboard")) {
                        try {
                            java.lang.reflect.Method method = window.getClass().getMethod("loadDataTabel");
                            method.invoke(window);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data di database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Input Harga dan Stok harus berupa angka!", 
                    "Format Salah", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormEditBarang dialog = new FormEditBarang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbGradeKopi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
