/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gudangkopi.view;

/**
 *
 * @author mulqi
 */
public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    String buttonStyle = "arc: 99; background: null; borderWidth: 1; focusWidth: 0; borderColor: #fff;";

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {  
    
    initComponents();
    
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);  
    
        contentPanel.revalidate();
        contentPanel.repaint();

        try {    
        
            ClassLoader classLoader = MainFrame.class.getClassLoader();
            
            btnDashboard.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("assets/SideBar/Dashboard.svg", classLoader).derive(25, 25));
            btnBarangMasuk.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("assets/SideBar/BarangMasuk.svg", classLoader).derive(25, 25));
            btnBarangKeluar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("assets/SideBar/BarangKeluar.svg", classLoader).derive(25, 25));
            btnLaporan.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("assets/SideBar/Laporan.svg", classLoader).derive(25, 25));
            btnKeluar.setIcon(new com.formdev.flatlaf.extras.FlatSVGIcon("assets/SideBar/Keluar.svg", classLoader).derive(25, 25));

            java.net.URL logoURL = classLoader.getResource("assets/SideBar/Logo.png");
            if (logoURL != null) {
                javax.swing.ImageIcon imageIcon = new javax.swing.ImageIcon(logoURL);
                java.awt.Image image = imageIcon.getImage(); 
                java.awt.Image newImg = image.getScaledInstance(80, 80, java.awt.Image.SCALE_SMOOTH); 
                lblLogo.setIcon(new javax.swing.ImageIcon(newImg));      
            } else {
                System.err.println("File Logo.png tidak ditemukan lewat ClassLoader!");
            }
        } catch (Exception e) {
            System.err.println("Gagal memuat aset GUI menggunakan ClassLoader!");
            e.printStackTrace();
        }                 
   
    // jarak antar icon dan teks 
        btnDashboard.setIconTextGap(10);
        btnBarangMasuk.setIconTextGap(10);
        btnBarangKeluar.setIconTextGap(10);
        btnLaporan.setIconTextGap(10);
        lblLogo.setIconTextGap(15);
  
        btnKeluar.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, buttonStyle);
              
    //swtich page
        pindahHalaman(btnDashboard, "dashboard"); // ini halaman pertama nya ya bang

        btnDashboard.addActionListener(e -> pindahHalaman(btnDashboard, "dashboard"));
        btnBarangMasuk.addActionListener(e -> pindahHalaman(btnBarangMasuk, "barang_masuk"));
        btnBarangKeluar.addActionListener(e -> pindahHalaman(btnBarangKeluar, "barang_keluar"));
        btnLaporan.addActionListener(e -> pindahHalaman(btnLaporan, "Laporan")); 
         
       
    }
    
    private void pindahHalaman(javax.swing.JButton buttonAktif, String namaCard) {
        // restart tombol
        String styleNormal = "arc: 12; background: null; borderWidth: 0; focusWidth: 0; foreground: #ffffff;";
        
        javax.swing.JButton[] semuaTombol = {btnDashboard, btnBarangMasuk, btnBarangKeluar, btnLaporan};
        
        for (javax.swing.JButton btn : semuaTombol) {
            
         btn.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, styleNormal);
         btn.setContentAreaFilled(false); 
         btn.setOpaque(false);
         
         }
        
        // tombol aktif
        String styleAktif = "arc: 12; background: #2064E1; foreground: #ffffff; borderWidth: 0; focusWidth: 0;";
        buttonAktif.putClientProperty(com.formdev.flatlaf.FlatClientProperties.STYLE, styleAktif);
        buttonAktif.setContentAreaFilled(true); 
        buttonAktif.setOpaque(false);
        
        // render
        for (javax.swing.JButton btn : semuaTombol) {
        btn.revalidate();
        btn.repaint();
        }
        
        //card layout switch halaman
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, namaCard);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        pageDashBoard = new com.mycompany.gudangkopi.view.dashboard();
        pageBarangKeluar = new com.mycompany.gudangkopi.view.barangKeluar();
        pageBarangMasuk = new com.mycompany.gudangkopi.view.barangMasuk();
        pageLaporan = new com.mycompany.gudangkopi.view.laporan();
        sidebarPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnBarangMasuk = new javax.swing.JButton();
        btnBarangKeluar = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(947, 600));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());
        contentPanel.add(pageDashBoard, "dashboard");
        contentPanel.add(pageBarangKeluar, "barang_keluar");
        contentPanel.add(pageBarangMasuk, "barang_masuk");
        contentPanel.add(pageLaporan, "Laporan");

        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        sidebarPanel.setBackground(new java.awt.Color(33, 44, 62));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(278, 0));

        menuPanel.setBackground(new java.awt.Color(33, 44, 62));
        menuPanel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        menuPanel.setPreferredSize(new java.awt.Dimension(200, 100));
        menuPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 4));

        btnDashboard.setBackground(new java.awt.Color(33, 44, 62));
        btnDashboard.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setBorderPainted(false);
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);
        menuPanel.add(btnDashboard);

        btnBarangMasuk.setBackground(new java.awt.Color(33, 44, 62));
        btnBarangMasuk.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.setBorder(null);
        btnBarangMasuk.setBorderPainted(false);
        btnBarangMasuk.setContentAreaFilled(false);
        btnBarangMasuk.setFocusPainted(false);
        btnBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBarangMasuk.addActionListener(this::btnBarangMasukActionPerformed);
        menuPanel.add(btnBarangMasuk);

        btnBarangKeluar.setBackground(new java.awt.Color(33, 44, 62));
        btnBarangKeluar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnBarangKeluar.setText("Barang Keluar");
        btnBarangKeluar.setBorder(null);
        btnBarangKeluar.setBorderPainted(false);
        btnBarangKeluar.setContentAreaFilled(false);
        btnBarangKeluar.setFocusPainted(false);
        btnBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPanel.add(btnBarangKeluar);

        btnLaporan.setBackground(new java.awt.Color(33, 44, 62));
        btnLaporan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("Laporan Transaksi");
        btnLaporan.setBorder(null);
        btnLaporan.setBorderPainted(false);
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setFocusPainted(false);
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPanel.add(btnLaporan);

        btnKeluar.setBackground(new java.awt.Color(33, 44, 62));
        btnKeluar.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        lblLogo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(255, 255, 255));
        lblLogo.setText("Gudang Kopi Pak Parman");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(sidebarPanel, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarangKeluar;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel menuPanel;
    private com.mycompany.gudangkopi.view.barangKeluar pageBarangKeluar;
    private com.mycompany.gudangkopi.view.barangMasuk pageBarangMasuk;
    private com.mycompany.gudangkopi.view.dashboard pageDashBoard;
    private com.mycompany.gudangkopi.view.laporan pageLaporan;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
